name: mrcardoso
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9502989421598613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e2020'
    - '#f6eae0'
    - '#ce422b'
    - '#c0b7b0'
    - '#76716e'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
