name: mrcardoso
favicon: null
layout_spectrum: 0.26377641945146024
typography_spectrum: 0.9502989421598613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010006'
    - '#471b16'
    - '#c74d22'
    - '#eaba77'
    - '#e7e2cd'
  brandStrength: 0.6654275511391461
  lightness: 0.49435227317735553
  saturation: 0.3125
  rhythmicContrast: 0.05355663108639419
purpose: []
